select * from customer;

-- what is the total revenue generated by male vs female customers ?

select gender , sum(purchase_amount) as total_revenue_$ from customer group by gender;

-- which customers use the discount but still paid more than average purchase amount

select * from (
	select * , avg(purchase_amount) over() as avg_amount 
    from customer
    ) as derived_table
where purchase_amount>=avg_amount;

-- what are the top 5 products with highest average review rating 
select item_purchased, round(avg(review_rating),2) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;

-- compare the average purchase amounts between standard and express shipping

select shipping_type,round(avg(purchase_amount),2) as avg_purchase_amount, sum(purchase_amount) as total_purchase_amount
from customer 
where shipping_type="Standard" or shipping_type="Express"
group by shipping_type;

-- do subscribed customers spend more ? compare average and total revenue between subscribers and non subscribers
select subscription_status, 
	count(*) as total_count,
	round(avg(purchase_amount), 2) as avg_purchase_amount, 
    sum(purchase_amount) as total_purchase_amount
from customer
group by subscription_status;


-- which 5 products have highest percentage of purchases with discount applied

select item_purchased,
	round(100 * sum(case when discount_applied="Yes" then 1 else 0 end)/ count(*),2 ) as discount_purchase_rate
from customer
group by item_purchased
order by discount_purchase_rate desc
limit 5;

-- segement customers into new, returning and loyal based on their total number of previous purchases and 
-- show the count of each segement

with customer_segement_type as(
	select customer_id, previous_purchases,
    case when previous_purchases<2 then "new"
		when previous_purchases between 2 and 10 then "returning"
        else "loyal"
        end as customer_type
	from customer
) 
select customer_type, count(*) as total_count
from customer_segement_type
group by customer_type;

-- what are top 3 most purchased products with each category

select *
from (
	select category, 
		item_purchased, 
		sum(purchase_amount) as purchase_amount_per_item,
		rank() over( partition by category order by sum(purchase_amount) desc) as rank_number
	from customer
    group by category, item_purchased
	) as t
where rank_number<=3;

-- what are top 3 most purchased products with each category based on count of orders

select category, item_purchased, purchased_count
from (
	select category, item_purchased, 
			count(*) as purchased_count,
            row_number() over (partition by category order by count(*) desc) as rn
            from customer
            group by category, item_purchased
		) as t
where rn<=3;

-- are customers who are repeat buyers ( more than 5 previous purchases) also likely to suscribe?
select subscription_status,
	count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status
order by repeat_buyers desc;

-- what is revenue constrbution by each age group 

select age_group,
	sum( purchase_amount) as total_revenue_by_age_group
from customer
group by age_group
order by total_revenue_by_age_group desc;

